### ISSUE TITLE
Saving image issue

### ISSUE THREAD

**Issue by harshsri2208** [harshsri2208/MEME#3]
On pressing the save button after creating the meme, it shows the message "saved!" but the meme is not saved anywhere in the internal storage.

**Comment by alfianyusufabdullah** [comment]
Can i work on this @harshsri2208 ?

**Comment by harshsri2208** [comment]
Yes you can. Should I assign this issue to you?

**Comment by harshsri2208** [comment]
This issue has been resolved. The image was getting saved in the internal storage, it was just not visible in the gallery.

**Comment by alfianyusufabdullah** [comment]
Hi @harshsri2208 ! Yess, in this PR #4 , i just clean up code for future maintenance.

**Comment by harshsri2208** [comment]
@alfianyusufabdullah thanks. I will have a look

**Comment by alfianyusufabdullah** [comment]
Maybe you can make issue for redesign UI/UX @harshsri2208

**Comment by harshsri2208** [comment]
@alfianyusufabdullah  I have added the issue
