### ISSUE TITLE
Add contribute.md

### ISSUE THREAD

**Issue by harshsri2208** [harshsri2208/MEME#7]
This issue is for beginners who want to participate in hacktoberfest 2019. You can send a pull request for adding contribute.md file (which will tell the contributors how to contribute to this repo).
Contribute.md file will be similar to an average contribute.md file in various other repositories.

**Comment by dhrubo55** [comment]
hi @harshsri2208  can i work on this please?

**Comment by dhrubo55** [comment]
@harshsri2208 can you kindly review the pull request and let me know if you want some modifications otherwise can you merge it

**Comment by harshsri2208** [comment]
Yes sure

**Comment by harshsri2208** [comment]
Thanks @dhrubo55 for the contribute.md file. Nice work.
